# Generated by Django 4.2.7 on 2023-11-04 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_membership_company_members'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('company', 'user')},
        ),
    ]
