# Generated by Django 4.2.7 on 2023-11-07 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='company_receivers',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='company.company'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
