# Generated by Django 4.2.7 on 2023-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assignment', 'assignment'), ('addrequest', 'addrequest'), ('requestaccept', 'requestaccept'), ('information', 'information')], default='information', max_length=13),
        ),
    ]
